
package View;

import Model.User;
import dao.UserDAO;
import javax.swing.JOptionPane;



public class ChangePassword extends javax.swing.JFrame {
    private static User curentUser;
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword( User curentUser) {
        this.curentUser = curentUser;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OldPs = new javax.swing.JLabel();
        NewPs = new javax.swing.JLabel();
        BtChange = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        InputUsername = new javax.swing.JTextField();
        InputOldPs = new javax.swing.JPasswordField();
        InputNewPs = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChangePassword");

        OldPs.setText("Password");

        NewPs.setText("New Password");

        BtChange.setText("Change Password");
        BtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtChangeActionPerformed(evt);
            }
        });

        Username.setText("Username");

        InputOldPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputOldPsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(BtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NewPs)
                            .addComponent(OldPs, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(InputOldPs)
                            .addComponent(InputNewPs))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(InputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OldPs)
                    .addComponent(InputOldPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewPs)
                    .addComponent(InputNewPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(BtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // BUTTON change Password
    private void BtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtChangeActionPerformed
        String us = InputUsername.getText();
        String oldPs = new String(InputOldPs.getPassword());      
        String newPs =  new String(InputNewPs.getPassword());  
        
        if(curentUser!= null){
            if(curentUser.getPassword().equals(oldPs)){               
                boolean update = UserDAO.getInstance().ChangePassword(us,oldPs,newPs);                
                if(update){                  
                    curentUser.setPassword(newPs);
                    System.out.println("change successfull");
                    JOptionPane.showMessageDialog(this, "change successfull", "", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    System.out.println("mat khau khong dung");
                    JOptionPane.showMessageDialog(this, "change faied", "", JOptionPane.ERROR_MESSAGE);
                }    
            }
            else{
                System.out.println("mat khau khong dung");
                JOptionPane.showMessageDialog(this, "change faied", "", JOptionPane.ERROR_MESSAGE);
            }
        }   
        System.out.println("chua co nguoi dung");
        new InfoUser(curentUser);
        this.dispose();
    }//GEN-LAST:event_BtChangeActionPerformed

    private void InputOldPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputOldPsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputOldPsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword(curentUser);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtChange;
    private javax.swing.JPasswordField InputNewPs;
    private javax.swing.JPasswordField InputOldPs;
    private javax.swing.JTextField InputUsername;
    private javax.swing.JLabel NewPs;
    private javax.swing.JLabel OldPs;
    private javax.swing.JLabel Username;
    // End of variables declaration//GEN-END:variables
}
