
package View;

import Model.Booking;
import Model.Comment;
import Model.Room;
import Model.User;
import dao.BookingDAO;
import dao.CommentDAO;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;


public class CheckOutAndComment extends javax.swing.JFrame {
    private static ArrayList<Booking> bookingRoom;
    private static User currentUser;
    private static Room room;
    public CheckOutAndComment(User currentUser) {
        this.currentUser = currentUser;
        this.setUndecorated(true);
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbComments = new javax.swing.JLabel();
        BtBack = new javax.swing.JButton();
        Bconfirm = new javax.swing.JButton();
        InputComments = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comments (User)");

        LbComments.setText("Nhập đánh giá của bạn:");

        BtBack.setText("Back");
        BtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBackActionPerformed(evt);
            }
        });

        Bconfirm.setText("Gửi");
        Bconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(BtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(LbComments, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(InputComments, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbComments)
                    .addComponent(InputComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtBack)
                    .addComponent(Bconfirm))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // BUTTON back
    private void BtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackActionPerformed
        new HomeUser(currentUser);
        this.dispose();
    }//GEN-LAST:event_BtBackActionPerformed
    
    // BUTTON Confirm thực hiên dao thêm đánh giá
    private void BconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconfirmActionPerformed
        String comment = InputComments.getText();
        String name = currentUser.getName();
        bookingRoom = BookingDAO.getInstance().selectById(name);
        
        if (bookingRoom == null || bookingRoom.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chưa đặt phòng không thể đánh giá!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean found = false;
        
        for(Booking b : bookingRoom){
            if(b.getName().equals(name)){
                LocalDateTime checkInDate = b.getCheckIn();
                LocalDateTime checkOutDate = b.getCheckOut();
                String number = b.getNumber();
                
                Comment cm = new Comment(name,number,checkInDate,checkOutDate,comment);
                CommentDAO.getInstance().insert(cm);
                
                System.out.println("Da gui danh gia!");
                JOptionPane.showMessageDialog(null, "Đã gửi đánh giá"); 
                InputComments.setText("");
                found = true;
                break;   
            }         
        }
        
        if(!found){
            JOptionPane.showMessageDialog(null, "Chưa đặt phòng không thể đánh giá!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }       
    }//GEN-LAST:event_BconfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutAndComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutAndComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutAndComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutAndComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutAndComment(currentUser);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bconfirm;
    private javax.swing.JButton BtBack;
    private javax.swing.JTextField InputComments;
    private javax.swing.JLabel LbComments;
    // End of variables declaration//GEN-END:variables
}
