package View;

import Model.Comment;
import Model.Room;
import Model.User;
import dao.CommentDAO;
import dao.RoomDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class Comments extends javax.swing.JFrame {
    private static User currentUser;
    private DefaultTableModel tableModel;
    
    public Comments(User currentUser) {
        this.currentUser = currentUser;
        this.setUndecorated(true);
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
         tableModel = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho phép chỉnh sửa ô nào trong bảng
            }
        };
        tableModel.setColumnIdentifiers(new String[]{"id","Name","Number","CheckIn","CheckOut","Comment"});
        TableComments.setModel(tableModel);
        loadData();
    }
    
     private void loadData() {
        tableModel.setRowCount(0);
        ArrayList<Comment> list = CommentDAO.getInstance().selectAll();
        for(Comment c: list){
            tableModel.addRow(new Object[]{c.getId(),c.getName(),c.getNumber(),c.getCheckIn(),c.getCheckOut(),c.getComment()});
        }
        TableComments.getColumnModel().getColumn(0).setPreferredWidth(50);  
        TableComments.getColumnModel().getColumn(1).setPreferredWidth(180); 
        TableComments.getColumnModel().getColumn(2).setPreferredWidth(150); 
        TableComments.getColumnModel().getColumn(3).setPreferredWidth(250); 
        TableComments.getColumnModel().getColumn(4).setPreferredWidth(250); 
        TableComments.getColumnModel().getColumn(5).setPreferredWidth(180);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableComments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ViewComment");

        BtHome.setText("Home");
        BtHome.setToolTipText("");
        BtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHomeActionPerformed(evt);
            }
        });

        TableComments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableComments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCommentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableComments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(BtHome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(BtHome)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // BUTTON Home
    private void BtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeActionPerformed
        new HomeAdmin(currentUser);
        this.dispose();
    }//GEN-LAST:event_BtHomeActionPerformed
    
    // Chọn vào đánh giá để xóa
    private void TableCommentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCommentsMouseClicked
         int selectedRow = TableComments.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Bạn có chắc chắn muốn xóa đánh giá này?", 
                "Xác nhận xóa", 
                javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                // Xóa comment khỏi database
                String roomNumber = tableModel.getValueAt(selectedRow, 2).toString();
                CommentDAO.getInstance().delete(roomNumber);

                // Xóa khỏi bảng hiển thị
                tableModel.removeRow(selectedRow);

                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
            }
        }
    }//GEN-LAST:event_TableCommentsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comments(currentUser);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtHome;
    private javax.swing.JTable TableComments;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
