package View;

import Model.Room;
import Model.User;


public class HomeUser extends javax.swing.JFrame {
    private static User curentUser;
    private static Room room;
  

    public HomeUser(User curentUser) {
        this.curentUser = curentUser;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleHITHotelManager = new javax.swing.JLabel();
        BtInfo = new javax.swing.JButton();
        BtLogOut = new javax.swing.JButton();
        BtDatPhong = new javax.swing.JButton();
        BComments = new javax.swing.JButton();
        ListRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeUser");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TitleHITHotelManager.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        TitleHITHotelManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleHITHotelManager.setText("HIT HotelManager");

        BtInfo.setText("Thông tin tài khoản");
        BtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInfoActionPerformed(evt);
            }
        });

        BtLogOut.setText("Đăng xuất");
        BtLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLogOutActionPerformed(evt);
            }
        });

        BtDatPhong.setText("Đặt Phòng");
        BtDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDatPhongActionPerformed(evt);
            }
        });

        BComments.setText("Đánh giá và góp ý");
        BComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCommentsActionPerformed(evt);
            }
        });

        ListRoom.setText("Các phòng đã đặt");
        ListRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TitleHITHotelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(406, 406, 406))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(ListRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BComments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(TitleHITHotelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BComments)
                    .addComponent(ListRoom))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtDatPhong)
                    .addComponent(BtInfo))
                .addGap(74, 74, 74)
                .addComponent(BtLogOut)
                .addGap(173, 173, 173))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // BUTTON LogOut
    private void BtLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLogOutActionPerformed
       new Login(curentUser);
       this.dispose();
       if(curentUser!= null){
           System.out.println("Dang xuat thanh cong");
           curentUser = null;
           System.out.println("CurentUser: " + curentUser);
       }    
    }//GEN-LAST:event_BtLogOutActionPerformed

    
    // BUTTON Info
    private void BtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInfoActionPerformed
       new InfoUser(curentUser);       
       this.dispose();
       if(curentUser != null ){
           System.out.println("thong tin tai khoan: ");
           curentUser.display();
       }
       else{
           System.out.println("khong co nguoi dung");
       }
       
    }//GEN-LAST:event_BtInfoActionPerformed

    private void BtDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDatPhongActionPerformed
        new BookRoom(curentUser, room);       
        this.dispose();
        System.out.println("thuc hien tim phong");
    }//GEN-LAST:event_BtDatPhongActionPerformed
    
    // BUTTON đáng giá và góp ý
    private void BCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCommentsActionPerformed
        new CheckOutAndComment(curentUser);
        this.dispose();
    }//GEN-LAST:event_BCommentsActionPerformed

    private void ListRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRoomActionPerformed
        new ListRoomCustomer(curentUser);
        this.dispose();
    }//GEN-LAST:event_ListRoomActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser(curentUser);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComments;
    private javax.swing.JButton BtDatPhong;
    private javax.swing.JButton BtInfo;
    private javax.swing.JButton BtLogOut;
    private javax.swing.JButton ListRoom;
    private javax.swing.JLabel TitleHITHotelManager;
    // End of variables declaration//GEN-END:variables
}
