package View;

import Model.Room;
import Model.User;
import dao.RoomDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class ListRoomAdmin extends javax.swing.JFrame {
    
    private static User currentUser;
    private static DefaultTableModel tableModel;

    public ListRoomAdmin( User currentUser) {
        initComponents();
        this.currentUser = currentUser;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
           
         tableModel = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho phép chỉnh sửa ô nào trong bảng
            }
        };
        tableModel.setColumnIdentifiers(new String[]{"id","Number","Type","Price","Status"});
        tableRoom.setModel(tableModel);
        loadData();
    }
    private void loadData() {
        tableModel.setRowCount(0);
        ArrayList<Room> list = RoomDAO.getInstance().selectAll();
            for(Room r: list){
                tableModel.addRow(new Object[]{r.getId(),r.getNumber(),r.getType(),r.getPrice(),r.getStatus()});
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtBack = new javax.swing.JButton();
        OptionRoom = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRoom = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ListRoom (admin)");

        BtBack.setText("Back");
        BtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBackActionPerformed(evt);
            }
        });

        OptionRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Available", "Occupied", "MainTenance" }));
        OptionRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionRoomActionPerformed(evt);
            }
        });

        tableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRoomMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableRoom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(OptionRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(BtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(BtBack)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(OptionRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // BUTTON Back to home admin
    private void BtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackActionPerformed
        new HomeAdmin(currentUser);
        this.dispose();
        System.out.println("nguoi dung hien tai: " + currentUser.getName());
    }//GEN-LAST:event_BtBackActionPerformed

    private void OptionRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionRoomActionPerformed
        String option = (String)OptionRoom.getSelectedItem();
        ArrayList<Room> list = RoomDAO.getInstance().selectAll();
        tableModel.setRowCount(0);
        for(Room r: list){
            if(option.equals("Tất cả") || r.getStatus().equals(option)){
                tableModel.addRow(new Object[]{r.getId(),r.getNumber(),r.getType(),r.getPrice(),r.getStatus()});
            }
        }
    }//GEN-LAST:event_OptionRoomActionPerformed

    private void tableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRoomMouseClicked
//        int selectRow = tableRoom.getSelectedRow();
//        if(selectRow != -1){
//            String roomNumber = tableModel.getValueAt(selectRow,1).toString();
//            InputNumber.setText(roomNumber);
//            String type = tableModel.getValueAt(selectRow,2).toString();
//            InputType.setText(type);
//            String Price = tableModel.getValueAt(selectRow,3).toString();
//            InputPrice.setText(Price);
//        }
    }//GEN-LAST:event_tableRoomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListRoomAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListRoomAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListRoomAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListRoomAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListRoomAdmin(currentUser);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBack;
    private javax.swing.JComboBox<String> OptionRoom;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableRoom;
    // End of variables declaration//GEN-END:variables
}
