package View;

import Model.Booking;
import Model.Room;
import Model.User;
import dao.BookingDAO;
import dao.RoomDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



public class ListRoomCustomer extends javax.swing.JFrame {
    private static DefaultTableModel tableModel;
    private static User currentUser;
    
    public ListRoomCustomer(User currentUser) {
        initComponents();
        this.currentUser = currentUser;
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        tableModel = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho phép chỉnh sửa ô nào trong bảng
            }
        };
        tableModel.setColumnIdentifiers(new String[]{"Number","Name","Type","Price"});
        ListRoom.setModel(tableModel);
        loadData();
    }
    private void loadData() {
        tableModel.setRowCount(0);
        ArrayList<Booking> list = BookingDAO.getInstance().selectById(currentUser.getName());
            for(Booking r: list){
                tableModel.addRow(new Object[]{r.getNumber(),r.getName(),r.getType(),r.getPrice()});
            }    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListRoom = new javax.swing.JTable();
        BtHome = new javax.swing.JButton();
        LBCheckOut = new javax.swing.JLabel();
        BtBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ListRoom");

        ListRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListRoomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListRoom);

        BtHome.setText("Home");
        BtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHomeActionPerformed(evt);
            }
        });

        LBCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBCheckOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBCheckOut.setText("Bấm vào phòng để trả phòng!");

        BtBill.setText("Xem Hóa Đơn");
        BtBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(LBCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtHome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(BtBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LBCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtHome)
                    .addComponent(BtBill))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeActionPerformed
        new HomeUser(currentUser);
        this.dispose();
    }//GEN-LAST:event_BtHomeActionPerformed
    
    // Sự kiện trả phòng
    private void ListRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListRoomMouseClicked
        int selectedRow = ListRoom.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Bạn có chắc chắn muốn trả phòng này?", 
                "Xác nhận trả phòng", 
                javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                
                String roomNumber = tableModel.getValueAt(selectedRow, 0).toString();

                // cập nhật lại trạng thái phòng trong database
                RoomDAO.getInstance().updateStatus(roomNumber,"Available");
                
                // xóa khỏi database
                BookingDAO.getInstance().delete(roomNumber);

                // Xóa khỏi bảng hiển thị
                tableModel.removeRow(selectedRow);
                javax.swing.JOptionPane.showMessageDialog(this, "Trả phòng thành công!");
            }
        }
    }//GEN-LAST:event_ListRoomMouseClicked
    
    // Button xem bill
    private void BtBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBillActionPerformed
        new CustomerBill(currentUser);
        this.dispose();
        System.out.println("thuc hien xem hoa don");
    }//GEN-LAST:event_BtBillActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListRoomCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListRoomCustomer(currentUser);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBill;
    private javax.swing.JButton BtHome;
    private javax.swing.JLabel LBCheckOut;
    private javax.swing.JTable ListRoom;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
